[versions]
# AppCompat
app_compat_constraint_layout_version = "1.1.3"

# AndroidX
androidx_browser = "1.5.0"

# Kotlin
kotlin_version = "1.9.0"

# Serialization
json_version = "20220924"

# General
indicative_version = "1.1.0"
matomo_version = "4.1.0"

# Classpaths
android_tools_build_gradle_version = "8.4.0"
detekt_version = "1.23.3"

# Testing
mockk_version = "1.12.0"
robolectric_version = "4.10.3"
android_support_test_runner_version = "1.0.2"
android_support_test_espresso_core_version = "3.0.2"




[libraries]
# AppCompat
app-compat-contraint-layout = { module = "com.android.support.constraint:constraint-layout", version.ref = "app_compat_constraint_layout_version" }

# AndroidX
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx_browser" }

# Kotlin
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_version" }

# Serialization
# https://mvnrepository.com/artifact/org.json/json
json = { module = "org.json:json", version.ref = "json_version" }

# General
# https://mvnrepository.com/artifact/com.indicative.client.android/Indicative-Android
indicative = { module = "com.indicative.client.android:Indicative-Android", version.ref = "indicative_version" }
# https://jitpack.io/#matomo-org/matomo-sdk-android
matomo-android = { module = "com.github.matomo-org:matomo-sdk-android", version.ref = "matomo_version" }

# Classpaths
# https://mvnrepository.com/artifact/com.android.tools.build/gradle
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android_tools_build_gradle_version" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
# https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-gradle-pluginaar
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt_version" }
# https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-formatting
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt_version" }


# Testing
# https://mvnrepository.com/artifact/io.mockk/mockk
mockk = { module = "io.mockk:mockk", version.ref = "mockk_version" }
# https://mvnrepository.com/artifact/org.robolectric/robolectric
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric_version" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test-junit
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin_version" }
# https://mvnrepository.com/artifact/androidx.test/runner
android-support-test-runner = { module = "com.android.support.test:runner", version.ref = "android_support_test_runner_version" }
# https://mvnrepository.com/artifact/com.android.support.test.espresso/espresso-core
android-support-test-espresso-core = { module = "com.android.support.test.espresso:espresso-core", version.ref = "android_support_test_espresso_core_version" }
